# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount_proto/discount.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x64iscount_proto/discount.proto\"0\n\x0fGenerateRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\r\x12\x0e\n\x06length\x18\x02 \x01(\r\"\"\n\x10GenerateResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"\x1e\n\x0eUseCodeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"!\n\x0fUseCodeResponse\x12\x0e\n\x06result\x18\x01 \x01(\r2y\n\x0f\x44iscountService\x12\x36\n\rGenerateCodes\x12\x10.GenerateRequest\x1a\x11.GenerateResponse\"\x00\x12.\n\x07UseCode\x12\x0f.UseCodeRequest\x1a\x10.UseCodeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'discount_proto.discount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=33
  _globals['_GENERATEREQUEST']._serialized_end=81
  _globals['_GENERATERESPONSE']._serialized_start=83
  _globals['_GENERATERESPONSE']._serialized_end=117
  _globals['_USECODEREQUEST']._serialized_start=119
  _globals['_USECODEREQUEST']._serialized_end=149
  _globals['_USECODERESPONSE']._serialized_start=151
  _globals['_USECODERESPONSE']._serialized_end=184
  _globals['_DISCOUNTSERVICE']._serialized_start=186
  _globals['_DISCOUNTSERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
